language: cpp

compiler:
        - gcc

before_install:
        - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
        - sudo add-apt-repository -y ppa:boost-latest/ppa
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -qq update

install:
        - sudo apt-get install cmake 
        - sudo apt-get install -qq boost1.55
        - if [ "$CXX" == "g++"     ]; then .travis_scripts/gcc.sh; fi

script: 
        - mkdir build; pushd build;
        - cmake -D CMAKE_CXX_FLAGS=--coverage .. && make debug && make -j 2 run_test
        - popd;

after_success:
        - .travis_scripts/coveralls.sh
